### ISSUE TITLE
runtime error and need help

### ISSUE THREAD

**Issue by MakDon** [PhillippOhlandt/pmtoapib#3]
I am not familiar with go and i tried to make it work. I think i made some mistake but i couldn't find it out. Need some help and thank very much!
What i did:

1. yum install go
2. git clone and cd into the folder
3. go build (without arguments)
4. ./pmtoapib -collection collection.json -destination docs

and it return errors:
`./pmtoapib -collection collection.json -destination docs
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x52caba]

goroutine 1 [running]:
text/template.errRecover(0xc0000cdb58)
	/usr/lib/golang/src/text/template/exec.go:160 +0x1d0
panic(0x55b320, 0x6b4450)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
text/template.errRecover(0xc0000cc700)
	/usr/lib/golang/src/text/template/exec.go:160 +0x1d0
panic(0x55b320, 0x6b4450)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
main.CollectionItemRequest.ShortUrl(0xc000014060, 0x21, 0xc0000122ac, 0x4, 0xc0000b6000, 0x1, 0x4, 0xc000012328, 0x3, 0xc0000ba000, ...)
	/root/pmtoapib/CollectionItemRequest.go:19 +0x3a
reflect.Value.call(0x5741c0, 0xc0000c2250, 0x693, 0x583992, 0x4, 0x6dae08, 0x0, 0x0, 0x582560, 0x1, ...)
	/usr/lib/golang/src/reflect/value.go:447 +0x454
reflect.Value.Call(0x5741c0, 0xc0000c2250, 0x693, 0x6dae08, 0x0, 0x0, 0x0, 0x5b1e40, 0x5741c0)
	/usr/lib/golang/src/reflect/value.go:308 +0xa4
text/template.(*state).evalCall(0xc0000cc680, 0x56f9a0, 0xc0000c2240, 0x99, 0x5741c0, 0xc0000c2250, 0x693, 0x5b0e00, 0xc0000e86c0, 0xc0000105c9, ...)
	/usr/lib/golang/src/text/template/exec.go:695 +0x6bd
text/template.(*state).evalField(0xc0000cc680, 0x56f9a0, 0xc0000c2240, 0x99, 0xc0000105c9, 0x8, 0x5b0e00, 0xc0000e86c0, 0xc000045ed0, 0x1, ...)
	/usr/lib/golang/src/text/template/exec.go:585 +0xd78
text/template.(*state).evalFieldChain(0xc0000cc680, 0x56f9a0, 0xc0000c2240, 0x99, 0x56f9a0, 0xc0000c2240, 0x99, 0x5b0e00, 0xc0000e86c0, 0xc0000e4920, ...)
	/usr/lib/golang/src/text/template/exec.go:553 +0x220
text/template.(*state).evalFieldNode(0xc0000cc680, 0x56f9a0, 0xc0000c2240, 0x99, 0xc0000e86c0, 0xc000045ed0, 0x1, 0x1, 0x55b620, 0x6dae08, ...)
	/usr/lib/golang/src/text/template/exec.go:517 +0x113
text/template.(*state).evalCommand(0xc0000cc680, 0x56f9a0, 0xc0000c2240, 0x99, 0xc0000e8660, 0x55b620, 0x6dae08, 0x99, 0xc0000cc4d0, 0x4f1ef7, ...)
	/usr/lib/golang/src/text/template/exec.go:455 +0x725
text/template.(*state).evalPipeline(0xc0000cc680, 0x56f9a0, 0xc0000c2240, 0x99, 0xc0000e6480, 0x0, 0x0, 0x98)
	/usr/lib/golang/src/text/template/exec.go:429 +0x126
text/template.(*state).walk(0xc0000cc680, 0x56f9a0, 0xc0000c2240, 0x99, 0x5b0c80, 0xc0000e86f0)
	/usr/lib/golang/src/text/template/exec.go:254 +0x49b
text/template.(*state).walk(0xc0000cc680, 0x56f9a0, 0xc0000c2240, 0x99, 0x5b0ec0, 0xc0000e8540)
	/usr/lib/golang/src/text/template/exec.go:262 +0x142`

 
I tried to use it with docker but the download was very very very slow when downloading f54033cc70b6.

Thank you.

**Comment by MakDon** [comment]
The docker works becuase the network works again. Thanks
